scope.Scope{id: "global", label: "global"}.

scope.Defn{scopeID: I, span: S, name: N, kind: "rule"} :-
  ast.ruleDefn{id: I} &
  ast.ident{parentID: I, span: S, text: N}.

# scope.Var{scopeID: I, name: N, span: S, kind: "rule"} :-
#  XXX.

# scope.Placeholder{scopeID: I, span: S, kind: K} :-
#   XXX.

hl.mapping{rule: "repSepKW", type: "keyword"}.
hl.mapping{rule: "text", type: "string"}.
hl.mapping{rule: "bool", type: "bool"}.
hl.mapping{rule: "ident", type: "ident"}.
