person{name: "Paul", gender: "Male"}.
person{name: "Ann", gender: "Female"}.
father{child: "Pete", father: "Paul"}.
father{child: "Paul", father: "Peter"}.
father{child: "Ann", father: "Peter"}.
father{child: "Mary", father: "Mark"}.
father{child: "Bob", father: "John"}.
father{child: "Carolyn", father: "Paul"}.
father{child: "Henry", father: "Bob"}.

mother{child: "Pete", mother: "Mary"}.
mother{child: "Paul", mother: "Judith"}.
mother{child: "Ann", mother: "Judith"}.
mother{child: "Bob", mother: "Ann"}.
mother{child: "Mary", mother: "Carolyn K"}.
mother{child: "Carolyn", mother: "Mary"}.

