funcCall{id: 0, name: "map", numArgs: 2}.
lambda{body: 2, id: 1, numParams: 1, retType: "int"}.
letExpr{bindingID: 3, bodyID: 4, id: 2, varName: "x"}.
stringLit{id: 3, val: "hello"}.
funcCall{id: 4, name: "plus", numArgs: 2}.
var{id: 5, name: "x"}.
intLit{id: 6, val: 2}.
funcArg{exprID: 5, id: 7, idx: 0}.
funcArg{exprID: 6, id: 8, idx: 1}.
lambdaParam{id: 9, idx: 0, name: "x", ty: "int"}.
placeholder{id: 10}.
funcArg{exprID: 1, id: 11, idx: 0}.
funcArg{exprID: 10, id: 12, idx: 1}.
