letExpr{bindingID: 1, bodyID: 2, id: 0, varName: "x"}.
intLit{id: 1, val: 2}.
funcCall{id: 2, name: "toString", numArgs: 1}.
funcCall{id: 3, name: "plus2", numArgs: 1}.
var{id: 4, name: "x"}.
funcArg{argExprID: 4, callExprID: 3, idx: 0}.
funcArg{argExprID: 3, callExprID: 2, idx: 0}.

# have to plant these in the scope since there's no stdlib yet
builtin{name: "plus2", type: tapp{from: "int", to: "int"}}.
builtin{name: "toString", type: tapp{from: "int", to: "string"}}.
