letExpr{bindingID: 1, bodyID: 2, id: 0, varName: "x"}.
intLit{id: 1, val: 2}.
funcCall{id: 2, name: "plus2", numArgs: 1}.
intLit{id: 3, val: 2}.
funcArg{callExprID: 2, argExprID: 2, idx: 0}.

# added to help things along
scope_item{id: 0, name: "plus2", type: tapp{from: "int", to: "int"}}.
# this one shouldn't be necessary, but the scope chain rule isn't working
scope_item{id: 2, name: "plus2", type: tapp{from: "int", to: "int"}}.
stringLit{id: 100}.
lambda{id: 101}.
