internal.visualization{
  name: "Position over Time",
  spec: vegalite{
    mark: "line",
    encoding: encoding{
      x: mapping{field: "time", type: "quantitative"},
      y: mapping{field: "pos", type: "quantitative"}
    },
    query: sim{}
  }
}.

time{time: T} :-
  range{from: 1, to: 1000, val: T}.

pos{time: T, pos: Y} :-
  mul{a: T, b: 3, res: Y}.

sim{time: T, pos: Y} :-
  time{time: T} &
  pos{time: T, pos: Y}.
