export interface CancellationToken {}
export interface CompletionContext {}
export interface CompletionItem {}
export interface Definition {}
export interface Diagnostic {}
export interface DiagnosticCollection {}
export interface DocumentHighlight {}
export interface DocumentHighlightKind {}
export interface DocumentSymbol {}
export interface Location {}
export interface Position {}
export interface ProviderResult {}
export interface Range {}
export interface ReferenceContext {}
export interface SemanticTokens {}
export interface SemanticTokensBuilder {}
export interface SemanticTokensLegend {}
export interface SymbolInformation {}
export interface SymbolKind {}
export interface TextDocument {}
export interface WorkspaceEdit {}
