father{child: "Pete", father: "Paul"}.
father{child: "Paul", father: "Peter"}.
father{child: "Ann", father: "Peter"}.
father{child: "Mary", father: "Mark"}.
mother{child: "Pete", mother: "Mary"}.
mother{child: "Paul", mother: "Judith"}.
mother{child: "Ann", mother: "Judith"}.
mother{child: "Bob", mother: "Ann"}.
mother{child: "Mary", mother: "Carolyn K"}.

grandfather{grandchild: A, grandfather: C} :-
  parent{child: A, parent: B} &
  father{child: B, father: C}.

grandmother{grandchild: A, grandmother: C} :-
  child{child: A, parent: B} &
  mother{child: B, mother: C}.

grandparent{grandchild: A, grandparent: C} :-
  parent{child: A, parent: B} &
  parent{child: B, parent: C}.

parent{child: C, parent: P} :-
  mother{child: C, mother: P} | father{child: C, father: P}.

parents{child: C, mother: M, father: F} :-
  mother{child: C, mother: M} &
  father{child: C, father: F}.

sibling{left: L, right: R} :-
  parents{child: L, mother: M, father: F} &
  parents{child: R, mother: M, father: F}.

cousin{left: L, right: R} :-
  parent{child: L, parent: P1} &
  sibling{left: P1, right: P2} &
  parent{child: R, parent: P2}.
